### ISSUE TITLE
All groups lost after Firefox crash

### ISSUE THREAD

**Issue by oloendithas** [Morikko/sync-tab-groups#101]
Today FF has crashed because of memory overflow, then restarted normaly with all tabs from active group. After couple of hours I noticed that all groups are gone so as all backups. I can see only  backups made today after the crash and they all emty obviousy.
It's really sad to lose the data and the backup at once.

**Comment by Morikko** [comment]
I am sad you lose everything. However, your problem seems coming from
Firefox. The extension is only using the storage provided by Firefox. Back
ups can be removed only manually or when they exceed the max numbers. So,
it seems Firefox wipe off the data.

Are you using other extensions ? Did you lose also data ?

This is the reason there is an alternative back up system that download the
file.
Also, you can export your groups to save them out of Firefox.

Le 30 mars 2018 18:10, "oloendithas" <notifications@github.com> a écrit :

Today FF has crashed because of memory overflow, then restarted normaly
with all tabs from active group. After couple of hours I noticed that all
groups are gone so as all backups. I can see only backups made today after
the crash and they all emty obviousy.
It's really sad to lose the data and the backup at once.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Morikko/sync-tab-groups/issues/101>, or mute the thread

**Comment by oloendithas** [comment]
Not sure if other extensions have any data missing of which I would noticed, Gmail Checker ask to press refresh or something so maybe yes, FF lost all local storage. 
Regarding backups, maybe it would be better to rename the Local backup to, let's say, History? Because the backup word it's slightly missleading here, since it's stored in same place.
Anyway, thanks again for the great addon.
Cheers

**Comment by Morikko** [comment]
Yes, you are right renaming or adding some information about the storage
location could help.

Also, you might open a bug on bugzilla to help Mozilla to fix Firefox.
