### ISSUE TITLE
Data lost by switching Tab Group

### ISSUE THREAD

**Issue by Stormi1** [Morikko/sync-tab-groups#11]
Hello,
When I switch from one tab group to another and back again, data entered is lost.

**Comment by Morikko** [comment]
I need more information:
- which data have you lost: all, a group, some tabs ?
- about the tabs in the groups: a lot ? with pinned tabs ? 
- about the window: is it in private mode ?
- Can you reproduce it ?

**Comment by psisquared2** [comment]
I think he means that if I you enter something into a form on a website in group A (and you don't submit), then switch to group B and back to group A, the entered data is lost. Similar to what happens if you close the browser and reopen it.

I suspect this can't be fixed without additional API support?

**Comment by Morikko** [comment]
@psisquared2 In this case I can't do anything without the API. I am closing like you do when you click on the cross.

An alternative solution: multiple groups in multiple windows, so that you can keep the created data. A click on a group already open change the focus to the window.

**Comment by Stormi1** [comment]
Hello,
sorry for my bad english. I enter something in the form und submit it. Then I switch from Group A to group B and again to group A. Now, the form is emty. When I dont switch the group and restart the PC the data is not lost. Example: www.fielmann.de/status and enter a Number; then switch the group and the form ist empty. At next fill in some numbern in the form and restart the browser. The numbers are visible. I hop you understand what I mean.

**Comment by Stormi1** [comment]
"Duplicate Tab Shortcut" sollte das passende AddOn heißen....

**Comment by Morikko** [comment]
I can't change this behavior now with the current Firefox API.

**Explanation:**
 - When you quit Firefox and windows open again, Firefox restores your session. I can't keep session in the extension.
- When you close a group, tabs are closed like when you click on the cross. So all the temporary data is lost (like forms)

**Solution:**
 - Keep some groups open in multiple windows, so that you can keep critical tabs open

**In the future:**
 - Firefox might improve the API, to keep tabs loaded (See: [1384515 - Provide an API for hiding and showing individual tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1384515) )

**Comment by Stormi1** [comment]
Thank you
