### ISSUE TITLE
Tabs with different logins being reloaded on tab group switch

### ISSUE THREAD

**Issue by Mako-Aluveaux** [Morikko/sync-tab-groups#124]
IE two seperate Amazon logins
when switching to a different tab group will reload with the previous loaded tab group's cookies.

This may have been by design but
Perhaps adding a feature to isolate cookies between tab groups might be recommended.

**Comment by mikhoul** [comment]
IMO it's by design the goal of the extension it not to manage cookies or manage privacy.

If you want to manage your cookies like this between tabs there is already extensions dedicated to to this that you can use in conjunction with Sync Tab Group like https://chrome.google.com/webstore/detail/sessionbox-free-multi-log/megbklhjamjbcafknkgmokldgolkdfig?hl=fr

Regards :octocat:

**Comment by Morikko** [comment]
@mikhoul answered well your request. I won't manage the privacy. 
Other tools exist in both Firefox & Chrome to manage the privacy among your tabs.

And for Firefox: [Multi Account Container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)
