### ISSUE TITLE
Will STG retain tab history?

### ISSUE THREAD

**Issue by whiskytroll** [Morikko/sync-tab-groups#13]
I had Simplified Tab Groups (TG) installed when I used Ff 56, I'm now on Quantum and thus in need of a replacement. STG seems like a good replacement, I like the fact that you based the UI on TG.  If I install STG, will it detect and start to use the groups from TG? And will it remember the history of the tabs I have open? If so - will the history be retained even after switch between different groups?

Regards / Jesper

**Comment by Morikko** [comment]
Sorry but I can't... 

Due to the API, I won't be able to add hide/show tabs or keep tabs unloaded, so I am closing them. Thus: 
- Previous sessions (back button) are lost when closing a group
- Temporary data like forms are lost when closing a group
If something is really important, you can open group in other windows to keep some groups opened simultaneously.

Groups are not shared between Sync Tab Groups and any other extension (at least now). A solution is to save each groups in bookmarks. And then open each folders again in FF57 with the new extension.
It avoids all the tabs to open at once.

I am waiting FF API: [1384515 - Provide an API for hiding and showing individual tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1384515)

**Comment by whiskytroll** [comment]
I see. Well, I guessed that would be the case, since that's the same API TG's denshub is waiting for. I just hoped that you had found (made) a workaround. Not sharing groups isn't a huge bother for me, it's a one time set up after all, but I'd really like to retain history. I'll just have to wait for the API. Thanks for the answer!
