### ISSUE TITLE
Very high CPU utilization and Firefox crash

### ISSUE THREAD

**Issue by dcaravana** [Morikko/sync-tab-groups#14]
After installing this extension in my Firefox instance with hundreds of tabs opened in 10 different windows, CPU utilisation goes up for several minutes only to end in a Firefox crash.

I think the idea behind this extension is quite smart and I'd like to use it (#5 should be fixed ASAP as well) but this bug makes it unusable in my case.

I'm available to help with debugging.

**Comment by Morikko** [comment]
Can you confirm me the CPU rush with the v0.1.4 ?

#5 will be fixed with FF58, so in January. I will update the extension to be ready at the same time.

Sorry, for the inconvenience, I never used the extension with so much tabs/groups. I will do some tests soon.

**Comment by dcaravana** [comment]
No need to be sorry and thanks for your work! 👍 

I can confirm the problem it's still there.

Initially I thought it was gone but after a few minutes Firefox processes started to go crazy and eventually I had to disable your extension.

Interestingly CPU usage did not go down after disabling the extension, which is probably a sign that some other thing goes crazy in Firefox: in fact looking at the browser console I see a lot of HTTP requests going out to websites in my tabs (like someone is going around opening all of my tabs) and also a lot of errors in Screenshots.jsm (which I believe is part of Firefox itself).

Not exactly sure what's going on here, I hope this can help though.

**Comment by Morikko** [comment]
I  think I had the same problem with far less tabs. After CPU stopped, but I was unable to interact with Firefox UI anymore without quitting Firefox.

I suspect a overload of bookmark backup, also Firefox sync was rushing:
 - Did it too often, i reduce it 
 - Didn't respect async behavior -> can lead to many at the same time, I saw error probably due to cross deletion

Can you try the new version : https://github.com/Morikko/sync-tab-groups/tree/overload
 - Clone this repo
 - Load it from about:debugging tab by clicking on "Load Temporary Add-on" (select the manifest.json from the repo at the root)
 - Tell me if it is still going wrong

If my instructions are not enough clear, tell me, i will be more precise.

**Comment by dcaravana** [comment]
Instructions perfectly clear thanks.

I'm currently testing the app and things look a lot better.

I just had to amend the 5000 and put it back to 30000 because the second commit in that branch reverted it to 5000.

As a gut feeling (and a bit more looking at the Activity Monitor), the bookmark backup is clearly an heavy task that should be done quite rarely: in fact I can clearly see the CPU usage go up whenever that backup is done.

I'll let you know how it goes but Firefox appears to be performing well again.

**Comment by Morikko** [comment]
Change released with 0.1.5.

**Comment by Morikko** [comment]
@dcaravana Did you still have the problem ?

I do and christianlupus as swell in #20.

When it did happen, were you on a Linux/Unix system ?

**Comment by dcaravana** [comment]
I doesn't have a lot of time to try again, but I had it on my Mac (High Sierra).
I'll try again in a few days hopefully.

**Comment by Morikko** [comment]
Thanks. No worry, I opened an issue on bugzilla I am just looking for information in case of.
