### ISSUE TITLE
Sync across devices?

### ISSUE THREAD

**Issue by maddhin** [Morikko/sync-tab-groups#22]
Hi,
I'm still with FF56 as I need the workflow w/ groups but following the great development here closely and will switch as soon as possible. 

A maybe naive question: does "sync" mean "just" sync of the groups or sync across devices? 

If STG would have the ability to sync groups across devices this would be absolutely mind-boggling and THE tool I am looking for for years now!!!

**Comment by Morikko** [comment]
Sync is just about keeping groups correlated to a window. But, there is a thread about sync across devices #4. Also #9 is about sharing groups.

Since v0.2.1, you can save your groups as bookmarks in different subfolders. If you have a Firefox account, your bookmarks are shared and you can retrieve your url from other groups. However, you have to open/close it manually from the bookmarks. 

See example: [Bookmarks](https://addons.cdn.mozilla.net/user-media/previews/full/192/192882.png?modified=1511739464)

[Last summary post](https://github.com/Morikko/sync-tab-groups/issues/4#issuecomment-347049100)
