### ISSUE TITLE
Duplicate Bookmarks Folders

### ISSUE THREAD

**Issue by Jayaram-Jinaga** [Morikko/sync-tab-groups#31]
Thanks for this fantastic add-on. I am facing one issue with the feature, "Save groups in bookmarks automatically". The add-on is creating duplicate session folder every time, rather than using the existing session folder.

**Comment by Morikko** [comment]
So you end with something like this ? 
SyncTabGroups/
 - SessionFolder
 - SessionFolder
 - SessionFolder
....

It could be the case that folder are not removed. 

Are you on Linux or Windows ? 
Do you have messages in the FF web console (Ctrl+Maj+J) ?

**Comment by Jayaram-Jinaga** [comment]
Yes, exactly. I am on Windows 8.1. I forgot to view the console messages, when it had happened last time. I changed the folder name, and it is not happening now.

The issue seems to have happened, when I switched computers, though the other computer uses a different folder name. By the way, are you recreating the whole session folder, instead of just the window folder, when something changes? I will send console messages, if it happens next time.

One other minor niggle with this feature is, it is trying to rewrite bookmarks, even when I just switch tabs without changing url.

**Comment by Morikko** [comment]
Yes, the whole session is recreated.

Actually, at the beginning I visualized the bookmarks save just as a back up. Finally, many people like it because they can share tabs among devices. 

I personally don't like it because all tabs are always booked (and I have only one device). Also, too many bookmark operations are unstable on Linux.

So yes, I will update the bookmark soon when some other basic features would have been added. 

I close the issue as: 
 - It was "unique"
 - I will refact the bookmark code soon, so it won't be any more related.

Sorry for the disagreement.
