### ISSUE TITLE
Black artifacts and FF crash

### ISSUE THREAD

**Issue by ItayXD** [Morikko/sync-tab-groups#39]
Hi, whenever I enable the extension my firefox is basically unusable. I'm getting black artifacts and if I continue using it ultimately crashes

**Comment by Morikko** [comment]
What is your:
 - OS
 - Extension version

Do you have a screenshot of the artifacts ? 
Can you have access to the web console and tell me if do you see something ? (Ctrl+Maj+J)
In Preferences, do you have auto save enabled for bookmarks ? If yes, does it the same if disabled.

**Comment by Morikko** [comment]
Since v0.4.1: bookmark auto-save disabled; Next version will be totally different.

**Comment by ItayXD** [comment]
Hi, sorry I really didn't have the time to comment on this.
I was using arch 4.14, were you able to reproduce it? Should I try the next version?

**Comment by Morikko** [comment]
Don't worry, I just closed it because I changed the code a lot last weeks. Moreover, it is a problem that is probably from the bookmark auto-save. Especially, it was doing lots of troubles on Linux distribution.
The reasons: 
 - I was bookmarking every tabs from scratch at each save
 - Bookmarking is a very heavy operation

With too many tabs/groups, it could often finish by crashing. Since v0.4.1, this functionality is totally disabled until I will make it better.

You can try it again, sure. If you don't want to disturb your classic session do `firefox -ProfileManager -no-remote &` from the terminal and create a new profile. You will have a Firefox window not related to your other tabs and bookmarks.

If you have again the problem, can you try to report those information: 
> Do you have a screenshot of the artifacts ?
Can you have access to the web console and tell me if do you see something ? (Ctrl+Maj+J)
In Preferences, do you have auto save enabled for bookmarks ? If yes, does it the same if disabled.
