### ISSUE TITLE
FeatureRequest: add shortcuts

### ISSUE THREAD

**Issue by jackslayter** [Morikko/sync-tab-groups#8]
hi,
its possible to add shortcuts for example :
- to switching between groups (back, next)
- create new group

thank you for your job

**Comment by Morikko** [comment]
Shortcuts:
 - Switching between groups (back, next)
 - Create new group and switch to it
 - Move to next/previous open groups
 - Open Toolbar menu (preparing #19)
 - (Un)Synchronize current window
 - Save in bookmarks

As I will have to rewrite some parts of my core code, it will take me a bit more time. 

Do you have idea about shortcuts ? (i have no idea about what is reserved for example in other extensions)

I will see if I can let the shortcuts be set in settings. Because API is static and set in the code: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands
I would prefer to be more flexible.

**Comment by Morikko** [comment]
Since last shortcuts were sometimes conflicting (alt+shift+right was used as text selecting as well), what do you suggest as keyboard shortcuts ?

-----
Actual shortcuts:

Alt+Shift+Right | Switch to next closed group.
Alt+Shift+Left | Switch to previous closed group.
Alt+Shift+Insert | Create a new group and switch to it.
Alt+Shift+Up | Focus window with next group opened.
Alt+Shift+Down | Focus window with previous group opened.
Alt+Shift+Delete | Close and remove the current group in window and switch to next one.
Alt+Shift+Space | Open Sync Tab Group Menu.

----- 
I can't go against this API limitation:
 Key combinations must consist of two or three keys:
  * modifier (mandatory, except for function keys). This can be any of: "Ctrl", "Alt", "Command", "MacCtrl".
  * secondary modifier (optional). If supplied, this must be "Shift".
  * key (mandatory). This can be any one of:
        the letters A-Z
        the numbers 0-9
        the function keys F1-F12
        Comma, Period, Home, End, PageUp, PageDown, Space, Insert, Delete, Up, Down, Left, Right

**Comment by adc17** [comment]
@Morikko Is there any chance of making these customizable? I've used SimpleTabGroups in the past, which looks something like this:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/22868730/65397538-db842880-dd7e-11e9-86e1-a059542ebbd7.png">

**Comment by Morikko** [comment]
No sorry, it is a huge change I won't assume. You should probably stay on
simple tab groups if you want this customization.

Le lun. 23 sept. 2019 à 03:21, Alexander Chalk <notifications@github.com> a
écrit :
