### ISSUE TITLE
Notification after every backup

### ISSUE THREAD

**Issue by HarmtH** [Morikko/sync-tab-groups#86]
Since version 0.6.1 I'm getting a notification (Download Complete) after every backup, which is pretty annoying. I'm using Firefox 58.0.2 (Ubuntu 17.10 default). Is there any way to turn the notifications off for the backups?

**Comment by Morikko** [comment]
The extension doesn't trigger a notification, it only does a normal download not kept in the history.

Thus, two suggestions:
 - You have set an option in Firefox
 - You have another extension that creates notifications when you download

Soon, I will add another possibility to save the back up inside Firefox instead of in an external download.

**Comment by HarmtH** [comment]
Completely forgot I had an extension that created notifications for downloads. Think fix #79  in 0.6.1 triggered it. Luckily the extension has an option to not create notifications for quick downloads. Thanks!
