### ISSUE TITLE
Backup timer wrong? No 1 day or 1 week backups

### ISSUE THREAD

**Issue by maddhin** [Morikko/sync-tab-groups#88]
Hi,

I only have 5-min, 1h and 4h backups in my backup folder. 1-day and 1-week backups are missing. 

I see that the 4h backup is from 2 days ago, although I have been using the browser within the last 2 days. 

Is it possible, that STG makes backups based on a timer that starts when the browser starts? That would mean that STG / browser has to run 4h, 1 day or 1 week until a backup is made...?

I guess it would be good to implement something like a check when the last backup has been made instead of pure timer value. Or the whole thing is a different bug;)

I personally would love to have the option to have more backups - say every 5min, every hour for the last 6 hours, for the last 5 days and say 4 last weeks. But that would be almost too much and is certainly not a priority at the moment (although it might be good to have now as naturally now a lot of bugs/errors occur and backups are more valuable than in a super stable release haha) 

Cheers

**Comment by Morikko** [comment]
> I only have 5-min, 1h and 4h backups in my backup folder. 1-day and 1-week backups are missing.

Due to #82, recently your groups were corrupted. While corrupted, no save is done to avoid to corrupt the back-up as well.

Usually, after a corrupt detection, your groups saved in Firefox are loaded again. In #82, it always failed as the problem was in the opened tabs and always corrupted again. 

> Is it possible, that STG makes backups based on a timer that starts when the browser starts? That would mean that STG / browser has to run 4h, 1 day or 1 week until a backup is made...?

For now, yes. (not perfect, but it is an easy solution than do most of the job)

> I personally would love to have the option to have more backups - say every 5min, every hour for the last 6 hours, for the last 5 days and say 4 last weeks. But that would be almost too much and is certainly not a priority at the moment (although it might be good to have now as naturally now a lot of bugs/errors occur and backups are more valuable than in a super stable release haha)

That would be better but as you said it is not the priority. The priority was to have some back-up.

**Comment by maddhin** [comment]
hm, #82 was on a different computer and if I am not completely wrong now, the backups where "full" (not corrupted, ~900kB file size) and STG continued to backup. 

As all my groups / tabs disappeared on a second PC: would it be possible to rotate a few more backups? On the second machine the 1h & 4h backup also got corrupted although the problem must have occured between shutdown yesterday and start today = STG had no chance to run 1h or 4h. 
If STG got corrupted yesterday and it continued to work fine "on the surface", there should be a error message/warning so one can do a manual export of the groups and recovery.

**Comment by Morikko** [comment]
> hm, #82 was on a different computer and if I am not completely wrong now, the backups where "full" (not corrupted, ~900kB file size) 

That might be back up before the corruption.

> and STG continued to backup.

Before v0.6.1 yes, since v0.6.1 if a corruption is detected, the back up is canceled. Have you checked the file modification date ?

In any cases, I will investigate more.

> would it be possible to rotate a few more backups? 

What do you mean ?

> If STG got corrupted yesterday and it continued to work fine "on the surface", there should be a error message/warning so one can do a manual export of the groups and recovery.

2 cases: 

1. Your data is corrupted
 - The system automatically reload the groups from the disk (warning the users will only afraid them)
 - Special case:  like in #82 the corruption is coming back due to a recurrent problem in your open session
         - Wait the fixed release
         - Close all your windows (or only the problematic one if you can) and restart the browser, groups are not deleted just closed.
 - Only if the corruption is recurrent is a short time, I should add a message to the user to help and guide him. (To Do)

2. Your groups disappear
  - This is not a corruption, one might remove all its groups intentionally or not.
  - If it is a bug, usually the application doesn't know. So, I can't warn the user, nor a correction is done. However, this is my job to prevent those errors.

Note: If you uninstall the extension, your data in Firefox is removed --> your groups as well.

**Comment by maddhin** [comment]
@Morikko thanks for your detailed explanation!

I didn't uninstall the extention or anything, so it must be a bug that all groups/taps disappeared (as I mentioned: I switched off the computer in the evening and had the problem once I wanted to start working in the morning). 

For the backups: by "rotating" I mean that the extension saves several backups. Say the last three 4h backups. That would give more security as this should keep more backups and gives more time to react if there is a problem. There is a great little tool called "rSnapshot" for Linux backups which has a perfect "backup rotation system". 

The main point being that there are "reliable" automatic backups. Doing manual backups is of course good but we all know that the day is usually busy and it is very easy to forget to make a manual backup every few hours. 

I guess the bottom line is that the backup function should be more stable and "hardend" so it is a real fallback option if anything breaks. 

Last but not least: you are doing an amazing job with the extension, so, please, see this as constructive input and not as complaining. We are all very grateful to have this extension and - I guess - getting a little greedy with want to have it working prefectly-perfect! ;)

**Comment by Morikko** [comment]
> For the backups: by "rotating" I mean that the extension saves several backups. Say the last three 4h backups. That would give more security as this should keep more backups and gives more time to react if there is a problem. There is a great little tool called "rSnapshot" for Linux backups which has a perfect "backup rotation system".

The only difficulty is about how to manage the back ups.

## Download API (Now)
Now, I am using the download API because it is out of Firefox memory so less risky (lost groups happened with old Tab Groups extension when Firefox updated) and not removed when uninstalled. But also, It added constraints. Download icon is blinking and many people complain. On top of that I have not a complete control on the back up files. Either I keep the file in the history so that I can remove it later on. But, the users would be polluted by those back-ups in the download history. Or I can remove it from the history but then I lost the link to the file and I can't remove it on the disk.

As in v0.6.2, I chose to clean the history and keep the filename per timer identical, so that back-ups are overwritten. (If you have ideas, you are welcome)

## Extension Data (Future)
I have planned to add a feature to save back up in the extension data. I will have a complete control to create, fetch and erase those back-ups. Moreover, the download will not blink any more. 

Certainly a better solution than the current one with only 5 timers. I will probably switch to rotate back-up like this:
 - Choose the interval between 2 back ups (Example: 4 hours)
 - Choose the maximal time to keep backup (Example: 1 week)

-------
> The main point being that there are "reliable" automatic
automatic backups. Doing manual backups is of course good but we all know that the day is usually busy and it is very easy to forget to make a manual backup every few hours.

You are right, I can't expect every body to do this. But the extension is still young and I can't test it under all circumstances. On my development session and on my daily session, I have lost no groups since a while and the back ups are working fine. So the problem is either specific to your environment or more deeply hidden in the extension.

I will test again this weekend to check if I can find bugs. 

Just as a reminder: If your data is corrupted, the saves stop (make sense). Of course, I trying my best to avoid corrupted states! 

-----
> Last but not least: you are doing an amazing job with the extension, so, please, see this as constructive input and not as complaining. We are all very grateful to have this extension and - I guess - getting a little greedy with want to have it working prefectly-perfect! ;)

Although, you got troubles with the application and you keep courteous. Moreover, you are doing valuable feedback. In any cases, thank you for your support and help.

**Comment by Morikko** [comment]
Local back up is now available in v0.6.3.

**Comment by maddhin** [comment]
@Morikko super, thank you so mcuh for adding the backup option!!! Will test! ;)
